# Generated by Django 5.2 on 2025-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
