# Generated by Django 5.2 on 2025-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_myuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="avatar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
