# Generated by Django 5.2 on 2025-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_ordermodel_alter_orderprodcut_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="createdAt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="deliveryType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="fullname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="paymentType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="totalCost",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
